### ISSUE TITLE
Update base image of Authservice container image

### ISSUE THREAD

**Issue by cfryanr** [istio-ecosystem/authservice#101]
@AndrewBabbitt97 reports on a PR that he created and later closed:

> Disregard the change, however of note is that it looks like the version of debian your last release was built with has an issue with some ssl certs, found the reason my change worked wasnt the code change but by building the image using a newer version of the debian image.

See https://github.com/istio-ecosystem/authservice/pull/100#issuecomment-641721714

Sounds like we need to update base image of Authservice container image.

**Comment by nacx** [comment]
Starting from v1.0.0, the authservice builds `FROM scratch`, and it just contains the statically linked binary.
