### ISSUE TITLE
no basic auth credential

### ISSUE THREAD

**Issue by 13567436138** [istio-ecosystem/authservice#142]
[root@master01 ~]# docker pull docker.pkg.github.com/istio-ecosystem/authservice/authservice:0.4.0-2a89ce7
Error response from daemon: Head https://docker.pkg.github.com/v2/istio-ecosystem/authservice/authservice/manifests/0.4.0-2a89ce7: no basic auth credential

**Comment by 13567436138** [comment]
Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
[root@master01 ~]#

**Comment by yovizzle** [comment]
I'm getting the same issue

**Comment by gamberooni** [comment]
You can create a Personal Access Token according to the [docs](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token). Select the appropriate scopes and copy the generated token into a file (e.g. TOKEN.txt). Then do docker login using that token `$ cat TOKEN.txt | docker login https://docker.pkg.github.com -u USERNAME --password-stdin`. After that you should be able to do docker pull `$ docker pull docker.pkg.github.com/istio-ecosystem/authservice/authservice:0.4.0-2a89ce7`.

**Comment by nacx** [comment]
Images are pushed now to GHCR
