### ISSUE TITLE
Support adding ext_authz filter and using the authservice on the ingress gateway

### ISSUE THREAD

**Issue by cfryanr** [istio-ecosystem/authservice#15]
This is a feature originally proposed by @nickrmc83. I'm creating this github issue as a placeholder for Nick to add more details.

**Comment by peterhaochen47** [comment]
We tried putting the authservice into the same pod as the Istio ingress gateway, and adding the ext_authz filter to the filter chain of that gateway (along with JWT AuthN MeshPolicy), and everything seemed to work fine. 🎉

**Comment by Nelson0409** [comment]
> We tried putting the authservice into the same pod as the Istio ingress gateway, and adding the ext_authz filter to the filter chain of that gateway (along with JWT AuthN MeshPolicy), and everything seemed to work fine. 🎉

Would you mind sharing the details of "putting the authservice into the same pod as Istio ingress gateway"? Did you do that during installing Istio?
