### ISSUE TITLE
Change the inline OIDC client configuration to reference of a k8s secret.

### ISSUE THREAD

**Issue by incfly** [istio-ecosystem/authservice#151]
https://github.com/istio-ecosystem/authservice/issues/149#issuecomment-900449428

Currently configmap contains the inline OIDC client information. We should change this to a secret reference, such as,

```yaml
oidcClientSecret: <namespace-foo>/<secret-name-bar>
```

**Comment by incfly** [comment]
@anhdle14 could you take this? Thanks!

**Comment by nacx** [comment]
Support for storing the client secret in a k8s secret has been added in v1.0.0
