### ISSUE TITLE
Authservice pods are using high memory resources even when utilizing Redis caching

### ISSUE THREAD

**Issue by atoy3731** [istio-ecosystem/authservice#156]
In one of our more trafficked environments, we're noticing our authservice pods using all 4Gi of memory we're assigning to in our K8s resource limits, which is causing the pods to restart.

We're implementing HA and utilizing Redis for caching, so I wouldn't think the authservice pods themselves should be utilizing that high of memory. Perhaps it is a leak?

**Comment by incfly** [comment]
I indeed have reproduced the issue, https://github.com/incfly/authservice/tree/oom/test/perf contains some instructions of how to set this up. Once we obtained a session cookie for repeatable requests, i noticed the authservice itself memory does not shrink even after requests going down.

**Comment by incfly** [comment]
@Shikugawa BTW, I also spent a bit time to obtain the memprofile for the authservice when under load test. This is a memory allocation for 15s execution profile. 
[profile001.pdf](https://github.com/istio-ecosystem/authservice/files/7283758/profile001.pdf)

It has some setup steps needed to obtain the pprof memory profile rendering.  https://gperftools.github.io/gperftools/heapprofile.html We will need to add `LD_PRELOAD` env var to point to the authservice docker image's lib.so. And then have the process dump into some folder /tmp/xxx. And copy the profiler dump to local machine and render into pdf via pprof.

I don't have exact steps/manifest to get that for now. But let me know if you need to get this setup for investigation.

Thanks!

**Comment by Shikugawa** [comment]
resolved by #167
