### ISSUE TITLE
Start new flow to new fetch tokens when either the ID token or the access token has expired

### ISSUE THREAD

**Issue by cfryanr** [istio-ecosystem/authservice#17]
Currently, the authservice does not look at the user's tokens inside the cookie on subsequent requests. This choice was perhaps made because Istio already supports adding a Policy (with apiVersion "authentication.istio.io/v1alpha1") to validate JWT tokens on the `Authorization` header (see https://istio.io/docs/tasks/security/authn-policy/#end-user-authentication).  Assuming that you configure your app to use both the authservice for fetching tokens and the authentication policy for checking tokens, then the app is secured.

However, when the tokens inside that cookie expire, the user will not be able to access the app anymore. Presumably they would need to manually clear that cookie from their browser to convince the authservice to help them fetch new tokens.

Instead, the authservice could check the expiration dates of the tokens from the cookie on each request. A first draft of an improvement would be for the authserive to simply throw away the cookie and pretend that it was not there when it sees that one of the tokens inside the cookie has expired. That way, the authservice would help the user start the flow to obtain new tokens during that same request where it first detected that a token has expired.

A future iteration of this type of functionality could go a step further by using the refresh token, as described in issue #16, but the first draft described here would not need to be so sophisticated.

The ID token and the access token could potentially have different expiration dates. It might be worth considering ignoring one of them if the app is not interested in receiving that token type from the authservice, assuming that there were some way for the user to configure that.

It would also be worth considering if/how to handle opaque access tokens in the context of this feature. Presumably the authservice would have to make an http call to the OIDC server to ask if the token is still valid. Of course, this would have a performance implication.  This probably needs more conversation.

This line of thought perhaps opens the bigger question of whether or not the authservice should be doing full token validation of the tokens from the cookie on every request before putting them on the http headers for the app. One advantage of doing so would be that the user would not need to configure the Istio authentication policy for checking tokens, and thus avoid repeating the `issuer` and `jwksUri` settings between the authservice config and the authentication policy config.  Another advantage would be that we could support opaque access tokens, which are not supported by the Istio authentication policy.  This probably also needs more conversation.

@nickrmc83 What would you think of adding a feature like this to the beta milestone plan?

**Comment by cfryanr** [comment]
@nickrmc83 Is this effectively fixed by your recent pull request where you set the token cookies to expire based on the expiry date of the token itself?

**Comment by nickrmc83** [comment]
> @nickrmc83 Is this feature effectively implemented by your recent pull request where you set the token cookies to expire based on the expiry date of the token itself?

Yes. The cookie expiration should mean that the browser will stop sending them at which point the auth flow should be invoked again.
