### ISSUE TITLE
Create authservice 0.5.0 release

### ISSUE THREAD

**Issue by incfly** [istio-ecosystem/authservice#197]
We have made several changes recently. Including

- Fips build
- https://github.com/istio-ecosystem/authservice/pull/187
- dynamic jwks support.
- health check for jwks

This is worth a new release. The release should

- [x] Create release branch, release-0.5
- [x] Build the new image, with fips and non fips options. The https://github.com/istio-ecosystem/authservice/pull/196 is in flight.
- [x] Test both are working end to end with the bookinfo example, we provided. https://github.com/istio-ecosystem/authservice/tree/master/bookinfo-example
- [x] Document the release notes. 
- [x] Release via Github release, a previous one e.g. https://github.com/istio-ecosystem/authservice/releases/tag/0.4.1

**Comment by Shikugawa** [comment]
Finally, we released v0.5.0. https://github.com/istio-ecosystem/authservice/releases/tag/0.5.0
