### ISSUE TITLE
How to set the client secret from an existing kubernetes secret?

### ISSUE THREAD

**Issue by jcornaz** [istio-ecosystem/authservice#234]
Hi,

I don't want to hard-code the client secret in plain text in the config file. How can I reference a Kubernetes secret that contains the client secret?

**Comment by nacx** [comment]
Starting from v1.0.0 you can configure it with something like:
```json
"oidc": {
    "client_id": "fake-client-id",
    "client_secret_ref": {
        "namespace": "default",
        "name": "test-secret-1"
    }
}
```
