### ISSUE TITLE
Support `:` in client ID

### ISSUE THREAD

**Issue by mjnagel** [istio-ecosystem/authservice#263]
Currently authservice chains do not work if the client id contains a `:`. This is due to the usage of the [basic auth header](https://github.com/istio-ecosystem/authservice/blob/236079504552c295996de175df4cda5d1b58b17c/internal/http/http.go#L92) and [limitations on the user id not allowing `:` for basic auth](https://www.rfc-editor.org/rfc/rfc2617#section-2).

I'm not familiar with the alternative options here but I suspect switching from basic auth to <something else> would allow this to be supported. Alternatively this should be documented as a limitation with a clear error in the logs/when the config is read in. In the current state I see a failure on the token exchange with my IDP and `Invalid client or Invalid client credentials` in Authservice's logs. On the IDP side I am able to see the request come in with only part of my client id (it is trimmed at the first `:`).

This should be easy to reproduce by using a client id with a URI, such as `http://example.com`.

**Comment by nacx** [comment]
according [to the spec](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) clients may authenticate using basic auth or sending the client id and secret as body parameters, but the latter is not recommended, so I think the best thing is to validate the configuration and return a proper error message.
