### ISSUE TITLE
Setup CI/CD 

### ISSUE THREAD

**Issue by nickrmc83** [istio-ecosystem/authservice#31]
Create CI/CD configuration for running builds and test on all commits and MRs.

**Comment by cfryanr** [comment]
Limin suggested that we use Prow for CI.

**Comment by Changdrew** [comment]
We set up Github Actions to run `make test` on every PR. Do we want to also run on all commits?

**Comment by cfryanr** [comment]
We recently also added a github Actions Workflow to run tests on every commit to master, and added a badge to the main README file of the project which shows the status of master tests. We'll consider this first draft of CI finished because it is good enough for now.
