### ISSUE TITLE
log level flag error

### ISSUE THREAD

**Issue by peterhaochen47** [istio-ecosystem/authservice#4]
The pod containing the authservice is experiencing `CrashLoopBackOff` due to the log-level flag:
> kubectl logs -n istio-system transparent-auth-v1-55b5f5b849-bhx54
ERROR: Unknown command line flag 'log-level'

Changing [the Dockerfile CMD line](https://github.com/istio-ecosystem/authservice/blob/wip-code/build/Dockerfile.builder#L22) to `"--loglevel"` fixes this error. We also noticed that the [main function](https://github.com/istio-ecosystem/authservice/blob/wip-code/src/main/auth-server.cc#L89) requires `"--loglevel"` too.

**Comment by cfryanr** [comment]
This was fixed when the flag was renamed.
