### ISSUE TITLE
Put `__Host` back into the cookie names

### ISSUE THREAD

**Issue by cfryanr** [istio-ecosystem/authservice#41]
We accidentally removed the `__Host` prefix from the cookie names.  We should probably put that prefix back.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Cookie_prefixes for explanation of that prefix.

**Comment by nickrmc83** [comment]
@cfryanr I'll fix in #13

**Comment by nickrmc83** [comment]
Fixed as part of #42
