### ISSUE TITLE
Github Package Registry's `authservice` Alpha image should be public 

### ISSUE THREAD

**Issue by peterhaochen47** [istio-ecosystem/authservice#49]
Such that no auth is required to run `docker pull docker.pkg.github.com/istio-ecosystem/authservice/authservice:0.1.0-snapshot.1`

This is a follow-up from https://github.com/istio-ecosystem/authservice/issues/12

**Comment by Changdrew** [comment]
https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

**Comment by nacx** [comment]
Docker images are available in GHCR
