### ISSUE TITLE
Test that authservice can share both the ID token and the access token with the app

### ISSUE THREAD

**Issue by peterhaochen47** [istio-ecosystem/authservice#50]
This issue https://github.com/istio-ecosystem/authservice/issues/13 is closed and the related PR is merged. But the feature cannot be tested out until envoyproxy accepts, merges, and releases this PR: https://github.com/envoyproxy/envoy/pull/8668

This issue is a reminder to validate that the access feature describe in https://github.com/istio-ecosystem/authservice/issues/13 is working.

**Comment by cfryanr** [comment]
Tested on an environment with a sidecar built from source with the PR applied. We see this functioning correctly. Fantastic!
