### ISSUE TITLE
authservice should use Bearer Authorization headers

### ISSUE THREAD

**Issue by Changdrew** [istio-ecosystem/authservice#6]
When the authservice sets the token into the Authorization header for the app, it should follow the OAuth "Bearer Token Usage" standard https://tools.ietf.org/html/rfc6750#section-2.1. Specifically, the token value should be prepended with `Bearer ` (that's bearer with a capital B followed by a space character).

**Comment by peterhaochen47** [comment]
We also found that the Istio authn policy, the resulting JWT authn validation filter fails and returns a 401 error when there is no "Bearer " at the beginning of the Authentication header's value.

```
curl https://X.X.X.X/myapp -v -k -H 'authorization: <redacted_token>'
...<redacted for brevity>
< HTTP/2 401
< content-length: 29
< content-type: text/plain
< date: Mon, 30 Sep 2019 20:01:18 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 1
<
* Connection #0 to host 35.184.251.112 left intact
Origin authentication failed.
```

We also see that the request fails when the auth header starts with "bearer " (little "b"), so the capital "B" is important.
