### ISSUE TITLE
Compat with Istio v1.5?

### ISSUE THREAD

**Issue by haf** [istio-ecosystem/authservice#94]
Hello,

I was wondering if you're been testing authservice with Istio 1.5?

Regards
Henrik

**Comment by cfryanr** [comment]
We had manually tested the Authservice with the beta release of Istio 1.5 and found that it worked.

The project has not yet matured to the point of having automated integration tests which run against new versions of Istio.

Have you run into any trouble?

**Comment by haf** [comment]
No, we're just planning a bit over here. Thanks for replying =)
